services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: no
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=policy
      - MONGO_INITDB_ROOT_PASSWORD=policy1234
    volumes:
      - /c/dev/docker/mongodb/dataset:/data/db  # W:데이터 저장 경로
    networks:
      - network-mongo
    hostname: mongodb
  #----------------------------------------
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    container_name: mongo-express
    ports:
      - 27117:8081
    environment:
      - PORT=8081
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=policy
      - ME_CONFIG_MONGODB_ADMINPASSWORD=policy1234
      - ME_CONFIG_MONGODB_URL=mongodb://policy:policy1234@mongodb:27017/
    networks:
      - network-mongo
    hostname: mongo-express
#----------------------------------------
#========================================
networks:
  network-mongo:
    driver: bridge